# Copyright (c) 2026 TpyoKnig
# SPDX-License-Identifier: MIT

# ── Encryption key ────────────────────────────────────────────────────────────
# Generated by default. var.n8n_encryption_key overrides it: see the variable
# description for why: restoring a Postgres backup into a rebuilt deployment
# otherwise re-generates a key that cannot decrypt the credentials the restored
# database already holds.

resource "random_id" "n8n_encryption_key" {
  count = var.n8n_encryption_key == null && var.n8n_encryption_key_secret_ref == null ? 1 : 0

  byte_length = 32
}

locals {
  # null when n8n_encryption_key_secret_ref is set: there is no module-known
  # key value in that case, since the module never reads the caller's Secret
  # (see that variable's description for why). secretRefs.existingSecret
  # points the chart at the caller's own Secret name instead, below.
  n8n_encryption_key = var.n8n_encryption_key_secret_ref != null ? null : coalesce(var.n8n_encryption_key, try(random_id.n8n_encryption_key[0].hex, null))
}

# There is deliberately no check block warning about n8n_encryption_key, even
# though setting it wrongly is the most destructive single input mistake this
# module allows: a value that does not match the key the target database's
# credentials were encrypted under makes every one of them permanently
# unreadable, with no recovery path on n8n's side.
#
# Nothing checkable at plan time separates the safe uses from the unsafe one.
# The distinguishing fact is what the live database already holds, which no
# Terraform expression can read. An earlier version of this module warned
# whenever the input was combined with an external database, and that turned
# out to be precisely backwards:
#
#   - It fired on the intended use. Restoring a database into a rebuilt
#     deployment (the case the variable and the n8n_encryption_key output both
#     document as the reason this input exists) means restoring outside the
#     module and pointing at it with postgres_backend = "external". The warning
#     landed on the documented happy path.
#   - It stayed silent on the likeliest mistake: editing this value in tfvars on
#     a live deployment that already holds credentials under the generated key.
#     That plans clean, applies clean, and destroys every credential.
#
# A warning that fires on correct usage and passes the real error trains people
# to ignore it, so the guidance lives where it can be read before the apply
# instead: the variable description in variables.tf, the n8n_encryption_key
# output description, and README.md.

# ── Task runner auth token ─────────────────────────────────────────────────────
# Generated once and stored in state. Used as the shared secret between the n8n
# task broker (port 5679) and the runner sidecars on main and worker pods.
# Only active when n8n_task_runners_enabled = true.

resource "random_password" "task_runner_token" {
  length  = 32
  special = false
}

locals {
  # Per-credential key defaults when a *_secret_ref input's optional `key` is
  # omitted, resolved once here rather than in each variable's type
  # constraint (an omitted optional() attribute is null, not a useful
  # default), so the fallback is visible and testable in one place. null when
  # the corresponding *_secret_ref input itself is null; every reference below
  # guards on that separately.
  db_password_secret_ref_key      = var.db_password_secret_ref == null ? null : coalesce(var.db_password_secret_ref.key, "password")
  redis_auth_token_secret_ref_key = var.redis_auth_token_secret_ref == null ? null : coalesce(var.redis_auth_token_secret_ref.key, "password")
}

# ── Namespace ─────────────────────────────────────────────────────────────────
# Skipped when create_namespace = false: the caller deploys into a namespace
# that already exists. local.namespace_name below resolves to this resource's
# name when the module creates it, or to var.k8s_namespace directly otherwise;
# every other reference to the namespace name goes through that local, not
# through this resource, so it works on either path.

resource "kubernetes_namespace" "n8n" {
  count = var.create_namespace ? 1 : 0

  metadata {
    name = var.k8s_namespace
    # Managed-by label lets `kubectl get ns -l app.kubernetes.io/managed-by=...`
    # reliably find the module-owned namespace.
    labels = {
      "app.kubernetes.io/managed-by" = "terraform-kubernetes-n8n"
    }
  }

  timeouts {
    delete = "2m"
  }

}

locals {
  namespace_name = var.create_namespace ? kubernetes_namespace.n8n[0].metadata[0].name : var.k8s_namespace
}

# ── Secrets ───────────────────────────────────────────────────────────────────
# Three Secrets: core n8n config, the database password, and the Redis AUTH
# token. Each credential reaches the chart through a Secret reference rather
# than as a literal value, because a literal is written into the rendered Helm
# release values, which Helm then stores in its own release Secret in the
# cluster (sha256-addressed, retained per revision) on top of Terraform state.
# The task runner auth token is the exception: it encrypts nothing, so it is
# passed to the chart as a literal.

resource "kubernetes_secret" "n8n" {
  # Gated to zero only when n8n_encryption_key_secret_ref replaces this Secret
  # entirely: the chart's secretRefs.existingSecret names one Secret for all
  # four of N8N_ENCRYPTION_KEY, N8N_HOST, N8N_PORT and N8N_PROTOCOL, so there
  # is no way to keep this Secret around for the other three and still point
  # the encryption key at a caller-supplied one.
  count = var.n8n_encryption_key_secret_ref == null ? 1 : 0

  metadata {
    name      = "n8n-secrets"
    namespace = local.namespace_name
  }

  data = {
    N8N_ENCRYPTION_KEY = local.n8n_encryption_key
    N8N_HOST           = local.n8n_domain
    N8N_PORT           = "5678"
    N8N_PROTOCOL       = "http"
    WEBHOOK_URL        = coalesce(var.n8n_webhook_url, "https://${local.n8n_domain}")
  }
}

resource "kubernetes_secret" "n8n_db" {
  # Gated to zero when db_password_secret_ref points the chart at a Secret the
  # caller already manages instead. Single-purpose Secret, unlike
  # kubernetes_secret.n8n above, so the whole resource is skipped rather than
  # one key dropped from it. Only reachable on the external-database path: see
  # db_password_secret_ref's validation.
  # Also gated off on the CNPG path: CNPG generates the app-user credentials into
  # its own <cluster>-app Secret, which local.k8s_pg_secret_name points the chart
  # at. Ungated, this created an empty Secret (var.db_password is null there) that
  # nothing reads.
  count = var.db_password_secret_ref == null && !local.cnpg_enabled ? 1 : 0

  metadata {
    name      = "n8n-db-secret"
    namespace = local.namespace_name
  }

  data = {
    password = var.db_password
  }

}

# ── Redis AUTH secret ─────────────────────────────────────────────────────────
# The Redis AUTH token, on the same shape as the DB secret above. The chart
# mounts it as QUEUE_BULL_REDIS_PASSWORD on main, worker and webhook processor
# via redis.passwordSecret (see the Helm values below). Exists only on the
# opt-in path: there is no token to hold otherwise. local.redis_auth_token_value
# resolves to the caller-supplied var.redis_auth_token, see
# locals.tf.

resource "kubernetes_secret" "n8n_redis" {
  # Also gated on redis_auth_token_secret_ref: a caller-managed Secret needs no
  # module-managed twin. This resource was already indexed before that
  # addition (count already gated on local.redis_auth_active alone), so
  # narrowing the condition further does not move its address the way gating
  # kubernetes_secret.n8n and kubernetes_secret.n8n_db above does for the
  # first time; no `moved` block is needed here. See refactoring.tf.
  count = local.redis_auth_active && var.redis_auth_token_secret_ref == null ? 1 : 0

  metadata {
    name      = "n8n-redis-secret"
    namespace = local.namespace_name
  }

  data = {
    password = local.redis_auth_token_value
  }

}

# ── Service account ───────────────────────────────────────────────────────────
# Only created when var.n8n_image_pull_secrets is non-empty. Otherwise the chart
# creates the account and this resource does not exist; see the note on
# local.n8n_manages_service_account for why the module ever takes it over.
#
# The name is deliberately not the one the chart uses, so that enabling the
# input on a live deployment does not collide with the account Helm already
# owns; locals.tf has the full reasoning.
#
# automount_service_account_token is set explicitly because the provider
# defaults it to false, which would be a behaviour change: the chart leaves the
# field unset, and an unset ServiceAccount field means the pod mounts the token.

resource "kubernetes_service_account_v1" "n8n" {
  count = local.n8n_manages_service_account ? 1 : 0

  metadata {
    name      = local.n8n_service_account_name
    namespace = local.namespace_name
  }

  automount_service_account_token = true

  dynamic "image_pull_secret" {
    for_each = var.n8n_image_pull_secrets
    content {
      name = image_pull_secret.value
    }
  }

}


# ── Helm release ──────────────────────────────────────────────────────────────
# The n8n chart, rendered against the backing services selected by
# postgres_backend / redis_backend. The values tree is assembled in locals.tf
# (local.k8s_values_final) and wired to kubernetes_secret.n8n /
# kubernetes_secret.n8n_db / kubernetes_secret.n8n_redis.
# n8n_extra_helm_values is the escape hatch for chart knobs not exposed as
# typed inputs.

resource "helm_release" "n8n" {
  name             = "n8n"
  repository       = null
  chart            = "${var.n8n_chart_repository}/n8n"
  version          = var.n8n_chart_version
  namespace        = local.namespace_name
  create_namespace = false

  values = compact([
    yamlencode(local.k8s_values_final),
    var.n8n_extra_helm_values,
  ])

  timeout       = var.n8n_helm_timeout
  wait          = true
  wait_for_jobs = true

  # Without these, an
  # install that exceeds the timeout leaves the release in the cluster while
  # Terraform records no state for it, so every subsequent apply fails with
  # "cannot re-use a name that is still in use" and needs a manual helm
  # uninstall to recover.
  atomic          = true
  cleanup_on_fail = true

  depends_on = [
    kubernetes_namespace.n8n,
    kubernetes_secret.n8n,
    kubernetes_secret.n8n_db,
    kubernetes_secret.n8n_redis,
    helm_release.valkey,
    kubectl_manifest.cnpg_cluster,
    # Ordering, not just tidiness. When the pooler is enabled the release's
    # DB host points at the Pooler Service, so a release that rolls before the
    # Pooler exists starts pods against a name that does not resolve. They
    # CrashLoop, the release's own wait times out, and an atomic upgrade rolls
    # the whole thing back. Cheap edge, expensive absence.
    kubectl_manifest.cnpg_pooler,
    kubernetes_config_map_v1.task_runners_config,
  ]
}




# ── OpenTelemetry diagnostic check ─────────────────────────────────────────
# Warns at plan time when any n8n_otel_* tuning variable is set while the
# master toggle n8n_otel_enabled is false. The OTEL wiring above collapses
# the entire N8N_OTEL_* env-var block to [] when the master is off, silent
# by design, so without this check a caller who sets, e.g.,
# n8n_otel_exporter_otlp_endpoint without also flipping n8n_otel_enabled
# would wonder why no traces are flowing.
#
# `check` block (Terraform 1.5+) emits a warning, not an error, so plan and
# apply still succeed. This is intentional: some callers will legitimately
# stage tuning config in tfvars before flipping the master switch.

check "otel_tuning_requires_master_switch" {
  assert {
    condition = var.n8n_otel_enabled || (
      var.n8n_otel_exporter_otlp_endpoint == null &&
      var.n8n_otel_exporter_otlp_headers == null &&
      var.n8n_otel_exporter_service_name == null &&
      var.n8n_otel_traces_sample_rate == null &&
      var.n8n_otel_traces_include_node_spans == null &&
      var.n8n_otel_traces_inject_outbound == null &&
      var.n8n_otel_traces_production_only == null
    )
    error_message = "One or more n8n_otel_* tuning variables are set, but n8n_otel_enabled is false - the tuning values will be ignored and no N8N_OTEL_* env vars will be set on the n8n pods. Set n8n_otel_enabled = true to apply them, or clear the tuning variables to silence this warning."
  }
}

# ── Custom image guards ───────────────────────────────────────────────────────
# Six plan-time warnings for custom-image, extra-volume and pull-secret
# configurations that are accepted but almost certainly not what the caller
# meant. All are warnings rather than errors: each is legitimate in some
# deployment, and none can be decided with certainty from the inputs alone.
#
# Written as `guard ? body : true` per AGENTS.md, since Terraform 1.9 (the
# version floor) does not short-circuit && and ||.

check "custom_image_repository_needs_an_explicit_tag" {
  assert {
    condition     = var.n8n_image_repository != null ? var.n8n_image_tag != null : true
    error_message = "n8n_image_repository is set but n8n_image_tag is null, so the chart appends its own default and the release resolves to <repository>:stable. A custom registry rarely publishes a `stable` tag, and the pods then fail with ImagePullBackOff. Set n8n_image_tag to a tag that exists in this repository. Ignore this warning if the repository is a mirror that does publish `stable`."
  }
}

check "custom_image_tag_needs_a_task_runner_tag" {
  assert {
    condition = var.n8n_image_repository != null ? (
      var.n8n_task_runners_enabled ? (
        var.n8n_image_tag == null || var.n8n_task_runner_image_tag != null
      ) : true
    ) : true
    error_message = "A custom n8n image (n8n_image_repository + n8n_image_tag) is set with task runners enabled, but n8n_task_runner_image_tag is null. The chart tags the runner sidecar from the app image, so the sidecar resolves to n8nio/runners:<n8n_image_tag> and every main and worker pod fails with ImagePullBackOff unless that exact tag exists upstream, which fails the apply rather than completing with broken pods. Set n8n_task_runner_image_tag to the n8n version the custom image is built from. Ignore this warning if the custom image's tag is itself a published n8n version."
  }
}

check "custom_extensions_path_requires_a_source" {
  assert {
    # Two ways to put nodes at the path, so the warning has to rule out both:
    # a custom image that baked them in, or a volume mounted at or above it.
    condition = var.n8n_custom_extensions_path != null ? (
      var.n8n_image_repository != null ? true : anytrue([
        for mount in var.n8n_extra_volume_mounts :
        mount.mount_path == var.n8n_custom_extensions_path ||
        startswith(var.n8n_custom_extensions_path, "${mount.mount_path}/")
      ])
    ) : true
    error_message = "n8n_custom_extensions_path is set, but nothing in this configuration puts files there: n8n_image_repository is null, so the pods run the chart's stock image, and no n8n_extra_volume_mounts entry covers the path. n8n will scan an empty or missing directory and load no nodes, silently. Either point n8n_image_repository at an image with the compiled nodes baked in at this path, or mount a volume that carries them (see n8n_extra_volumes), or clear the path to silence this warning."
  }
}

check "extra_volumes_should_be_mounted" {
  assert {
    condition = alltrue([
      for volume in var.n8n_extra_volumes :
      contains([for mount in var.n8n_extra_volume_mounts : mount.name], volume.name)
    ])
    error_message = "An n8n_extra_volumes entry is never mounted, because no n8n_extra_volume_mounts entry names it. Kubernetes accepts an unmounted volume, so the pods will start and the files will simply not be there. Add a mount for it, or drop the volume. Ignore this warning only if the volume exists for something outside the n8n container."
  }
}

check "image_pull_secrets_need_a_custom_image" {
  assert {
    condition     = length(var.n8n_image_pull_secrets) > 0 ? var.n8n_image_repository != null : true
    error_message = "n8n_image_pull_secrets is set but n8n_image_repository is null, so every image the pods pull comes from a public registry: the chart's docker.n8n.io/n8nio/n8n and, with task runners on, n8nio/runners. Neither needs credentials, so the secrets are attached and never used. The cost is not zero: setting this input moves ownership of the ServiceAccount from the chart to the module. Clear it to hand the account back, or set n8n_image_repository to the private image these credentials are for."
  }
}

check "task_runner_image_tag_requires_task_runners" {
  assert {
    condition     = var.n8n_task_runner_image_tag != null ? var.n8n_task_runners_enabled : true
    error_message = "n8n_task_runner_image_tag is set, but n8n_task_runners_enabled is false, so no runner sidecar is deployed and the tag is ignored. Set n8n_task_runners_enabled = true to apply it, or clear the tag to silence this warning."
  }
}

# ── Supplementary webhook routing ─────────────────────────────────────────────
# The chart's webhook Ingress hardcodes its path list and renders four of the
# five prefixes n8n serves from the webhook processors, omitting /mcp. Values
# cannot extend it: ingress.webhookProcessor takes only enabled, className,
# annotations and tls.
#
# So the gap is real and silent: an MCP Server Trigger URL falls through to the
# main pods, which have no handler registered for it, and the editor's SPA
# route answers 200 with HTML. The caller sees a success and no execution.
# Verified live against chart 1.10.0 before this resource existed.
#
# Same host list, class, annotations and TLS secret as the chart's own, so the
# certificate is shared rather than duplicated and cert-manager still issues
# once. Only the paths differ.
#
# This disappears by itself when the chart starts rendering /mcp: add it to
# local.n8n_chart_routed_webhook_prefixes and the set this iterates goes empty.
resource "kubernetes_ingress_v1" "n8n_mcp" {
  count = var.create_ingress && length(local.n8n_unrouted_webhook_prefixes) > 0 ? 1 : 0

  metadata {
    name        = "n8n-webhook-processor-supplementary"
    namespace   = local.namespace_name
    annotations = local.k8s_ingress_annotations
    labels = {
      "app.kubernetes.io/name"       = "n8n"
      "app.kubernetes.io/component"  = "webhook-processor"
      "app.kubernetes.io/managed-by" = "Terraform"
    }
  }

  spec {
    ingress_class_name = var.k8s_ingress_class_name

    dynamic "rule" {
      for_each = local.k8s_ingress_hosts
      content {
        host = rule.value
        http {
          dynamic "path" {
            for_each = local.n8n_unrouted_webhook_prefixes
            content {
              path      = "${path.value}/"
              path_type = "Prefix"
              backend {
                service {
                  name = local.n8n_webhook_service_name
                  port {
                    number = local.n8n_service_port
                  }
                }
              }
            }
          }
        }
      }
    }

    tls {
      hosts       = local.k8s_ingress_hosts
      secret_name = local.k8s_ingress_tls_secret
    }
  }

  depends_on = [helm_release.n8n]
}
